// REGISTER ACTIONS
export const FETCH_USER_BY_KEY_INIT = 'FETCH_USER_BY_KEY_INIT';
export const FETCH_USER_BY_KEY_SUCCESS = 'FETCH_USER_BY_KEY_SUCCESS';

// AUTH ACTIONS
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

// APP PUBLIC DATA ACTIONS
export const FETCH_USER_PUBLIC_INFO_INIT = 'FETCH_USER_PUBLIC_INFO_INIT';
export const FETCH_USER_PUBLIC_INFO_SUCCESS = 'FETCH_USER_PUBLIC_INFO_SUCCESS';
