// REGISTER ACTIONS
export const FETCH_USER_BY_KEY_INIT = 'FETCH_USER_BY_KEY_INIT';
export const FETCH_USER_BY_KEY_SUCCESS = 'FETCH_USER_BY_KEY_SUCCESS';

// AUTH ACTIONS
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

// APP PUBLIC DATA ACTIONS
export const FETCH_USER_PUBLIC_INFO_INIT = 'FETCH_USER_PUBLIC_INFO_INIT';
export const FETCH_USER_PUBLIC_INFO_SUCCESS = 'FETCH_USER_PUBLIC_INFO_SUCCESS';

//GET USER PROFILE
export const FETCH_USER_PROFILE_INIT = 'FETCH_USER_PROFILE_INIT';
export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS';
export const FETCH_USER_PROFILE_FAIL = 'FETCH_USER_PROFILE_FAIL';

//GET ONE PROFILE
export const FETCH_ONE_PROFILE_INIT = 'FETCH_ONE_PROFILE_INIT';
export const FETCH_ONE_PROFILE_SUCCESS = 'FETCH_ONE_PROFILE_SUCCES';
export const FETCH_ONE_PROFILE_FAIL = 'FETCH_ONE_PROFILE_FAIL';

//GET TAGS
export const FETCH_TAGS_INIT = 'FETCH_TAGS_INIT';
export const FETCH_TAGS_SUCCESS ='FETCH_TAGS_SUCCESS';

// GET SUGGESTED PROFILES
export const FETCH_SUGGESTED_PROFILES_INIT = 'FETCH_SUGGESTED_PROFILES_INIT';
export const FETCH_SUGGESTED_PROFILES_SUCCESS ='FETCH_SUGGESTED_PROFILES_SUCCESS';
export const FETCH_SUGGESTED_PROFILES_FAIL = 'FETCH_SUGGESTED_PROFILES_FAIL'